[package]
name = "alchemy-game-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
rocket_ws = "0.1.0"
chrono = "0.4.31"
argon2 = "0.5.2"
argon_hash_password = "0.1.2"
serde = { version = "1.0", features = ["derive"] }
